Adds a new updateOffsetOnChange prop
okonet/react-container-dimensions pull request #26
Opened 2017-05-18 18:44 UTC by alexanderwallin

As discussed in #24, the `top` and `left` passed on to children components are not updated when they are changed, for instance when scrolling the page.

This is a quite naive solution, where we basically check `getBoundingClientRect()` on every frame. I couldn't come up with a reasonable alternative, since there are a ton of ways an element's offset can be changed. If you have an idea, that'd be great!

If we implement this, it should probably come with a friendly warning about the implementation.

2017-05-18 18:45 UTC, alexanderwallin commented
Oh, and I didn't intend to address linting issues or indentations, but was enforced by `lint-staged`. 😊

2017-05-19 18:34 UTC, okonet commented
I don't really like doing this on every frame. This will trash the layout and will probably have a severe impact on performance. Did you consider using something like https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver?

The more I think about this, the lesser I think this should be a part of this library, especially if this might have a performance drawbacks. If this issue can't be solved in a performant manner, I'll probably decline this PR. What do you think of it?

2017-05-19 18:35 UTC, okonet requested changes

2017-05-19 18:35 UTC, okonet commented on src/index.js
> +    if (ContainerDimensions.areRectsEqual(this.state, clientRect) === false) {
`!ContainerDimensions.areRectsEqual(this.state, clientRect)`?

2017-05-19 18:35 UTC, okonet commented on src/index.js
> +
Is this new line needed?

2017-05-19 18:35 UTC, okonet commented on src/index.js
> +    return ['top', 'right', 'bottom', 'left', 'width', 'height'].every(attr => rect1[attr] === rect2[attr])
Why not just iterating on all keys i.e. use a generic shallow compare?

2017-05-19 21:35 UTC, alexanderwallin commented on src/index.js
> +    return ['top', 'right', 'bottom', 'left', 'width', 'height'].every(attr => rect1[attr] === rect2[attr])
I just scoped it to what I was interested in, might as well be generic as for now.

2017-05-19 21:36 UTC, alexanderwallin commented on src/index.js
> +
Nope, accidental addition.

2017-05-19 21:38 UTC, alexanderwallin commented
I don't like this either. This solution fits better in a separate package. I'll have a look at `MutationObserver` tho!

2017-05-24 18:00 UTC, alexanderwallin commented
Okay, so neither `MutationObserver` or any of the other newer `*Observer` APIs work in this situation, since they watch DOM attributes or objects, whereas we are spying on the result of a function call.

We could do this in a couple of other ways:

* Provide a `scrollTargets` prop, where each target gets a scroll event listener that calls `onResize()`.
* Expose a new component (`<ContainerDimensionsWithScrollUpdates>`, or perhaps something less verbose) that has the `scrollTargets` functionality above, but renders `<ContainerDimesions>`, stores a ref on it and calls `this.storedRef.onResize()`.
* Expose a prop that simply triggers a call `onResize()` whenever it changes.

If none of these methods makes sense here, I'm happy to just create a new lil lib and provide it through there. 😊

2017-05-30 23:05 UTC, okonet commented
To be honest, I think the best option would be to have a separate HoC or HoF that is only concerned about scroll position. Based on that it's easy to calculate the realt top/left offsets. What do you think?

2019-07-02 06:19 UTC, closed without merging